/* Illuminated Life · the General Roman Calendar (data)
   The fixed celebrations of the General Roman Calendar, Ordinary Form, as it stands in 2026:
   the 2002/2008 Roman Missal plus the later decrees (through St John Henry Newman, 9 October,
   decree published 3 February 2026). Movable celebrations are computed in liturgy.js.

   One line each: "MMDD|rank|colour|name"
     rank    S solemnity · L feast of the Lord · F feast · M memorial · O optional memorial · A All Souls
     colour  w white · r red · v violet
   Names follow the English Missal, with "St" for "Saint". No texts of the Mass are included. */

window.IL = window.IL || {};

IL.CALENDAR = {
  general: [
    "0101|S|w|Mary, the Holy Mother of God",
    "0102|M|w|Sts Basil the Great and Gregory Nazianzen, Bishops and Doctors",
    "0103|O|w|The Most Holy Name of Jesus",
    "0107|O|w|St Raymond of Penyafort, Priest",
    "0113|O|w|St Hilary, Bishop and Doctor",
    "0117|M|w|St Anthony, Abbot",
    "0120|O|r|St Fabian, Pope and Martyr",
    "0120|O|r|St Sebastian, Martyr",
    "0121|M|r|St Agnes, Virgin and Martyr",
    "0122|O|r|St Vincent, Deacon and Martyr",
    "0124|M|w|St Francis de Sales, Bishop and Doctor",
    "0125|F|w|The Conversion of St Paul the Apostle",
    "0126|M|w|Sts Timothy and Titus, Bishops",
    "0127|O|w|St Angela Merici, Virgin",
    "0128|M|w|St Thomas Aquinas, Priest and Doctor",
    "0131|M|w|St John Bosco, Priest",

    "0202|L|w|The Presentation of the Lord",
    "0203|O|r|St Blaise, Bishop and Martyr",
    "0203|O|w|St Ansgar, Bishop",
    "0205|M|r|St Agatha, Virgin and Martyr",
    "0206|M|r|Sts Paul Miki and Companions, Martyrs",
    "0208|O|w|St Jerome Emiliani",
    "0208|O|w|St Josephine Bakhita, Virgin",
    "0210|M|w|St Scholastica, Virgin",
    "0211|O|w|Our Lady of Lourdes",
    "0214|M|w|Sts Cyril, Monk, and Methodius, Bishop",
    "0217|O|w|The Seven Holy Founders of the Servite Order",
    "0221|O|w|St Peter Damian, Bishop and Doctor",
    "0222|F|w|The Chair of St Peter the Apostle",
    "0223|M|r|St Polycarp, Bishop and Martyr",
    "0227|O|w|St Gregory of Narek, Abbot and Doctor",

    "0304|O|w|St Casimir",
    "0307|M|r|Sts Perpetua and Felicity, Martyrs",
    "0308|O|w|St John of God, Religious",
    "0309|O|w|St Frances of Rome, Religious",
    "0317|O|w|St Patrick, Bishop",
    "0318|O|w|St Cyril of Jerusalem, Bishop and Doctor",
    "0319|S|w|St Joseph, Spouse of the Blessed Virgin Mary",
    "0323|O|w|St Turibius of Mogrovejo, Bishop",
    "0325|S|w|The Annunciation of the Lord",

    "0402|O|w|St Francis of Paola, Hermit",
    "0404|O|w|St Isidore, Bishop and Doctor",
    "0405|O|w|St Vincent Ferrer, Priest",
    "0407|M|w|St John Baptist de la Salle, Priest",
    "0411|M|r|St Stanislaus, Bishop and Martyr",
    "0413|O|r|St Martin I, Pope and Martyr",
    "0421|O|w|St Anselm, Bishop and Doctor",
    "0423|O|r|St George, Martyr",
    "0423|O|r|St Adalbert, Bishop and Martyr",
    "0424|O|r|St Fidelis of Sigmaringen, Priest and Martyr",
    "0425|F|r|St Mark, Evangelist",
    "0428|O|r|St Peter Chanel, Priest and Martyr",
    "0428|O|w|St Louis Grignion de Montfort, Priest",
    "0429|M|w|St Catherine of Siena, Virgin and Doctor",
    "0430|O|w|St Pius V, Pope",

    "0501|O|w|St Joseph the Worker",
    "0502|M|w|St Athanasius, Bishop and Doctor",
    "0503|F|r|Sts Philip and James, Apostles",
    "0510|O|w|St John of Avila, Priest and Doctor",
    "0512|O|r|Sts Nereus and Achilleus, Martyrs",
    "0512|O|r|St Pancras, Martyr",
    "0513|O|w|Our Lady of Fatima",
    "0514|F|r|St Matthias, Apostle",
    "0518|O|r|St John I, Pope and Martyr",
    "0520|O|w|St Bernardine of Siena, Priest",
    "0521|O|r|St Christopher Magallanes, Priest, and Companions, Martyrs",
    "0522|O|w|St Rita of Cascia, Religious",
    "0525|O|w|St Bede the Venerable, Priest and Doctor",
    "0525|O|w|St Gregory VII, Pope",
    "0525|O|w|St Mary Magdalene de' Pazzi, Virgin",
    "0526|M|w|St Philip Neri, Priest",
    "0527|O|w|St Augustine of Canterbury, Bishop",
    "0529|O|w|St Paul VI, Pope",
    "0531|F|w|The Visitation of the Blessed Virgin Mary",

    "0601|M|r|St Justin, Martyr",
    "0602|O|r|Sts Marcellinus and Peter, Martyrs",
    "0603|M|r|Sts Charles Lwanga and Companions, Martyrs",
    "0605|M|r|St Boniface, Bishop and Martyr",
    "0606|O|w|St Norbert, Bishop",
    "0609|O|w|St Ephrem, Deacon and Doctor",
    "0611|M|r|St Barnabas, Apostle",
    "0613|M|w|St Anthony of Padua, Priest and Doctor",
    "0619|O|w|St Romuald, Abbot",
    "0621|M|w|St Aloysius Gonzaga, Religious",
    "0622|O|w|St Paulinus of Nola, Bishop",
    "0622|O|r|Sts John Fisher, Bishop, and Thomas More, Martyrs",
    "0624|S|w|The Nativity of St John the Baptist",
    "0627|O|w|St Cyril of Alexandria, Bishop and Doctor",
    "0628|M|r|St Irenaeus, Bishop, Martyr and Doctor",
    "0629|S|r|Sts Peter and Paul, Apostles",
    "0630|O|r|The First Martyrs of the Holy Roman Church",

    "0703|F|r|St Thomas, Apostle",
    "0704|O|w|St Elizabeth of Portugal",
    "0705|O|w|St Anthony Zaccaria, Priest",
    "0706|O|r|St Maria Goretti, Virgin and Martyr",
    "0709|O|r|Sts Augustine Zhao Rong, Priest, and Companions, Martyrs",
    "0711|M|w|St Benedict, Abbot",
    "0713|O|w|St Henry",
    "0714|O|w|St Camillus de Lellis, Priest",
    "0715|M|w|St Bonaventure, Bishop and Doctor",
    "0716|O|w|Our Lady of Mount Carmel",
    "0720|O|r|St Apollinaris, Bishop and Martyr",
    "0721|O|w|St Lawrence of Brindisi, Priest and Doctor",
    "0722|F|w|St Mary Magdalene",
    "0723|O|w|St Bridget, Religious",
    "0724|O|w|St Sharbel Makhluf, Priest",
    "0725|F|r|St James, Apostle",
    "0726|M|w|Sts Joachim and Anne, Parents of the Blessed Virgin Mary",
    "0729|M|w|Sts Martha, Mary and Lazarus",
    "0730|O|w|St Peter Chrysologus, Bishop and Doctor",
    "0731|M|w|St Ignatius of Loyola, Priest",

    "0801|M|w|St Alphonsus Liguori, Bishop and Doctor",
    "0802|O|w|St Eusebius of Vercelli, Bishop",
    "0802|O|w|St Peter Julian Eymard, Priest",
    "0804|M|w|St John Vianney, Priest",
    "0805|O|w|The Dedication of the Basilica of St Mary Major",
    "0806|L|w|The Transfiguration of the Lord",
    "0807|O|r|St Sixtus II, Pope, and Companions, Martyrs",
    "0807|O|w|St Cajetan, Priest",
    "0808|M|w|St Dominic, Priest",
    "0809|O|r|St Teresa Benedicta of the Cross, Virgin and Martyr",
    "0810|F|r|St Lawrence, Deacon and Martyr",
    "0811|M|w|St Clare, Virgin",
    "0812|O|w|St Jane Frances de Chantal, Religious",
    "0813|O|r|Sts Pontian, Pope, and Hippolytus, Priest, Martyrs",
    "0814|M|r|St Maximilian Kolbe, Priest and Martyr",
    "0815|S|w|The Assumption of the Blessed Virgin Mary",
    "0816|O|w|St Stephen of Hungary",
    "0819|O|w|St John Eudes, Priest",
    "0820|M|w|St Bernard, Abbot and Doctor",
    "0821|M|w|St Pius X, Pope",
    "0822|M|w|The Queenship of the Blessed Virgin Mary",
    "0823|O|w|St Rose of Lima, Virgin",
    "0824|F|r|St Bartholomew, Apostle",
    "0825|O|w|St Louis",
    "0825|O|w|St Joseph Calasanz, Priest",
    "0827|M|w|St Monica",
    "0828|M|w|St Augustine, Bishop and Doctor",
    "0829|M|r|The Passion of St John the Baptist",

    "0903|M|w|St Gregory the Great, Pope and Doctor",
    "0905|O|w|St Teresa of Calcutta, Virgin",
    "0908|F|w|The Nativity of the Blessed Virgin Mary",
    "0909|O|w|St Peter Claver, Priest",
    "0912|O|w|The Most Holy Name of Mary",
    "0913|M|w|St John Chrysostom, Bishop and Doctor",
    "0914|L|r|The Exaltation of the Holy Cross",
    "0915|M|w|Our Lady of Sorrows",
    "0916|M|r|Sts Cornelius, Pope, and Cyprian, Bishop, Martyrs",
    "0917|O|w|St Robert Bellarmine, Bishop and Doctor",
    "0917|O|w|St Hildegard of Bingen, Virgin and Doctor",
    "0919|O|r|St Januarius, Bishop and Martyr",
    "0920|M|r|Sts Andrew Kim Tae-gon, Priest, Paul Chong Ha-sang, and Companions, Martyrs",
    "0921|F|r|St Matthew, Apostle and Evangelist",
    "0923|M|w|St Pius of Pietrelcina, Priest",
    "0926|O|r|Sts Cosmas and Damian, Martyrs",
    "0927|M|w|St Vincent de Paul, Priest",
    "0928|O|r|St Wenceslaus, Martyr",
    "0928|O|r|Sts Lawrence Ruiz and Companions, Martyrs",
    "0929|F|w|Sts Michael, Gabriel and Raphael, Archangels",
    "0930|M|w|St Jerome, Priest and Doctor",

    "1001|M|w|St Thérèse of the Child Jesus, Virgin and Doctor",
    "1002|M|w|The Holy Guardian Angels",
    "1004|M|w|St Francis of Assisi",
    "1005|O|w|St Faustina Kowalska, Virgin",
    "1006|O|w|St Bruno, Priest",
    "1007|M|w|Our Lady of the Rosary",
    "1009|O|r|St Denis, Bishop, and Companions, Martyrs",
    "1009|O|w|St John Leonardi, Priest",
    "1009|O|w|St John Henry Newman, Priest and Doctor",
    "1011|O|w|St John XXIII, Pope",
    "1014|O|r|St Callistus I, Pope and Martyr",
    "1015|M|w|St Teresa of Jesus, Virgin and Doctor",
    "1016|O|w|St Hedwig, Religious",
    "1016|O|w|St Margaret Mary Alacoque, Virgin",
    "1017|M|r|St Ignatius of Antioch, Bishop and Martyr",
    "1018|F|r|St Luke, Evangelist",
    "1019|O|r|Sts John de Brébeuf and Isaac Jogues, Priests, and Companions, Martyrs",
    "1019|O|w|St Paul of the Cross, Priest",
    "1022|O|w|St John Paul II, Pope",
    "1023|O|w|St John of Capistrano, Priest",
    "1024|O|w|St Anthony Mary Claret, Bishop",
    "1028|F|r|Sts Simon and Jude, Apostles",

    "1101|S|w|All Saints",
    "1102|A|v|The Commemoration of All the Faithful Departed (All Souls)",
    "1103|O|w|St Martin de Porres, Religious",
    "1104|M|w|St Charles Borromeo, Bishop",
    "1109|L|w|The Dedication of the Lateran Basilica",
    "1110|M|w|St Leo the Great, Pope and Doctor",
    "1111|M|w|St Martin of Tours, Bishop",
    "1112|M|r|St Josaphat, Bishop and Martyr",
    "1115|O|w|St Albert the Great, Bishop and Doctor",
    "1116|O|w|St Margaret of Scotland",
    "1116|O|w|St Gertrude, Virgin",
    "1117|M|w|St Elizabeth of Hungary, Religious",
    "1118|O|w|The Dedication of the Basilicas of Sts Peter and Paul, Apostles",
    "1121|M|w|The Presentation of the Blessed Virgin Mary",
    "1122|M|r|St Cecilia, Virgin and Martyr",
    "1123|O|r|St Clement I, Pope and Martyr",
    "1123|O|w|St Columban, Abbot",
    "1124|M|r|Sts Andrew Dung-Lac, Priest, and Companions, Martyrs",
    "1125|O|r|St Catherine of Alexandria, Virgin and Martyr",
    "1130|F|r|St Andrew, Apostle",

    "1203|M|w|St Francis Xavier, Priest",
    "1204|O|w|St John Damascene, Priest and Doctor",
    "1206|O|w|St Nicholas, Bishop",
    "1207|M|w|St Ambrose, Bishop and Doctor",
    "1208|S|w|The Immaculate Conception of the Blessed Virgin Mary",
    "1209|O|w|St Juan Diego Cuauhtlatoatzin",
    "1210|O|w|Our Lady of Loreto",
    "1211|O|w|St Damasus I, Pope",
    "1212|O|w|Our Lady of Guadalupe",
    "1213|M|r|St Lucy, Virgin and Martyr",
    "1214|M|w|St John of the Cross, Priest and Doctor",
    "1221|O|w|St Peter Canisius, Priest and Doctor",
    "1223|O|w|St John of Kanty, Priest",
    "1226|F|r|St Stephen, the First Martyr",
    "1227|F|w|St John, Apostle and Evangelist",
    "1228|F|r|The Holy Innocents, Martyrs",
    "1229|O|r|St Thomas Becket, Bishop and Martyr",
    "1231|O|w|St Sylvester I, Pope"
  ],

  /* The Netherlands: what the national calendar changes, as far as we could establish.
     "raise" lifts a celebration of the general calendar to a higher rank (the patrons of Europe are feasts in Europe).
     "drop" removes a general entry that is kept on another day. "add" lines are proper celebrations.
     The diocesan calendars (Haarlem-Amsterdam, Utrecht, Roermond and the others) add more; they are not here. */
  nl: {
    raise: [["0214", "Cyril", "F"], ["0429", "Catherine of Siena", "F"], ["0711", "Benedict", "F"], ["0723", "Bridget", "F"], ["0809", "Teresa Benedicta", "F"]],
    drop: [["1221", "Canisius"]],
    add: [
      "0427|M|w|St Peter Canisius, Priest and Doctor",
      "0614|F|w|St Lidwina, Virgin",
      "0709|F|r|The Martyrs of Gorcum",
      "0727|M|r|St Titus Brandsma, Priest and Martyr",
      "1106|F|w|All the Holy Preachers of the Faith in the Netherlands",
      "1107|S|w|St Willibrord, Bishop, Patron of the Netherlands"
    ],
    highPriest: true // Our Lord Jesus Christ, the Eternal High Priest: feast, Thursday after Pentecost
  }
};
